<!DOCTYPE html>
<html lang="pt" amp>
<head>
	<meta charset="UTF-8">
	<title>Grantok Portas & Cabos</title>
	<link rel="alternate" hreflang="pt-br" href="alternateURL">
	<link rel="canonical" href="index.html">	
	<link rel="stylesheet" type="text/css" href="css/style.css">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<script type="text/javascript" src="js/troca-representantes.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script type="text/javascript" src="js/comboboxcidades.js"></script>	
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1,minimum-scale=1, user-scalable=no" />

	<script type="application/ld+json">
  		{
			"@context": "http://schema.org",
			"@type": "WebPage",
  			"publisher": "Maurício Spagnol"
  		}
  	</script>

<style amp-custom>
  body {
    background-color: white;
  }
</style>

<script type="text/javascript" src="js/scrolltop.js"></script>

</head>
<body>
	<div id="geral">
		<?php
			include("menu.php")
		?>
		<a href="#" class="scrollToTop"></a>
		<section>
			<!-- Image Map Generated by http://www.image-map.net/ -->
			<img src="img/mapa.PNG" usemap="#image-map" class="mapa" alt="mapa">

			<map itemprop="location" name="image-map">
			    <area onmouseover="repre(1)" target="" alt="Felix" title="Felix" href="" coords="196,190,203,192,214,189,223,197,235,195,237,216,230,218,230,233,223,233,213,235,207,232,200,236,189,234,195,219,191,208,191,206" shape="poly">
			    <area onmouseover="repre(2)" target="" alt="Silvio" title="Silvio" href="" coords="237,195,238,214,232,219,231,234,243,238,252,238,262,240,273,242,274,234,362,224,375,178,354,181,347,177,337,186,331,190,321,189,310,195,313,204,308,210,300,207,285,204,274,205,265,199" shape="poly">
			    <area onmouseover="repre(3)" target="" alt="Adriano" title="Adriano" href="" coords="277,236,340,230,352,250,349,257,345,265,313,294,312,316,282,315,283,292,291,267,287,253,276,245" shape="poly">
			    <area onmouseover="repre(4)" target="" alt="Everton" title="Everton" href="" coords="341,229,388,227,404,255,352,254,353,245" shape="poly">
			    <area onmouseover="repre(5)" target="" alt="Joao" title="Joao" href="" coords="345,269,358,293,403,259,354,257" shape="poly">
			    <area onmouseover="repre(6)" target="" alt="Remacol" title="Remacol" href="" coords="391,227,436,211,438,218,438,224,441,237,440,245,414,245,407,255" shape="poly">
			    <area onmouseover="repre(7)" target="" alt="Jairo" title="Jairo" href="" coords="216,264,255,264,257,279,280,295,239,338,194,312,217,285" shape="poly">
			    <area onmouseover="repre(8)" target="" alt="Maxi Venda" title="Maxi Venda" href="" coords="317,317,344,313,350,336,380,348,357,393,354,404,341,420,333,435,288,471,261,492,252,520,237,543,209,561,203,554,207,529,208,502,315,372,305,349,330,341,324,328" shape="poly">
			    <area onmouseover="repre(9)" target="" alt="Afonso" title="Afonso" href="" coords="214,235,215,282,107,283,142,255,165,250,184,235" shape="poly">
			    <area onmouseover="repre(10)" target="" alt="Fracaro" title="Fracaro" href="" coords="196,189,214,187,222,193,236,193,264,197,294,134,224,11,198,25,193,44,181,52,175,75,163,85,168,95,163,103,157,132,149,150,156,160,172,150,185,158" shape="poly">
			    <area onmouseover="repre(11)" target="" alt="Recrol" title="Recrol" href="" coords="258,67,352,91,393,64,384,36,371,23,338,27,326,19,286,9,269,3,266,11,226,8" shape="poly">
			    <area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="261,71,297,135,269,201,282,209,295,205,304,212,313,208,309,199,314,191,322,189,335,190,343,178,356,181,377,178,365,226,389,225,437,210,449,157,464,144,459,129,452,133,447,129,444,136,441,129,444,114,403,115,411,98,391,76,392,69,353,94" shape="poly">
   				<area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="447,249,431,305,401,322,383,347,352,335,346,312,315,317,315,294,342,270,356,297,408,258,414,259,414,248" shape="poly">
  			    <area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="208,504,313,370,299,348,328,338,314,318,281,319,281,299,238,343,188,314,213,284,101,285,93,289,98,296,86,296,5,390,42,381,82,428,103,418,193,479" shape="poly">
  			    <area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="217,262,216,235,231,235,273,245,290,261,282,293,261,280,258,261" shape="poly">

			</map>
			<div>
				<div id="representante_atual">
					<b><p align="middle" id="nome-repre-atual"></p></b><br>
					<p align="middle" id="telefone-repre-atual"></p><br>
					<p align="middle" id="e-mail-repre-atual"></p>
				</div>
				<h2 align="middle" id="titulo-representantes">Todos Representante</h2>
				<br>
				<div id="repre" align="middle"><b>FÉLIX SPEROTTO</b><br><br>
					<p>(49) 9 9917-1696</p>
					<p>dibisperotto@yahoo.com.br</p><br>
					<p>São Miguel do Oeste e Região</p>
					<button id="exibirComboboxfelix">Mostrar Cidades Atendidas</button>
					<select id="felix" hidden></select>
				</div>
				<div id="repre" align="middle"><b>SILVIO ZANCAN</b><br><br>
					<p>(49) 9 9202-0031</p>
					<p>silviofzancan@gmail.com</p><br>
					<p>Chapecó e Região</p>
					<button id="exibirComboboxsilvio">Mostrar Cidades Atendidas</button>
					<select id="silvio" hidden></select>
				</div>
				<div id="repre" align="middle"><b>ADRIANO BRITO</b><br><br>
					<p>(49) 9 9142-0302/3444-9870</p>
					<p>adrianorepre.vendas@gmail.com</p><br>
					<p>Concórdia e Região</p>
					<button id="exibirComboboxadriano">Mostrar Cidades Atendidas</button>
					<select id="adriano" hidden></select>
				</div>
				<div id="repre" align="middle"><b>EVERTON LONGEN</b><br><br>
					<p>(47) 9 9105-3859</p>
					<p>evertongrando@hotmail.com</p><br>
					<p>Rio do Sul e Região</p>
					<button id="exibirComboboxeverton">Mostrar Cidades Atendidas</button>
					<select id="everton" hidden></select>
				</div>
				<div id="repre" align="middle"><b>JOÃO STEFANELLO</b><br><br>
					<p>(49) 9 9107-8009</p>
					<p>joao.stefanello@gmail.com</p><br>
					<p>Lages e Região</p>
					<button id="exibirComboboxjoao">Mostrar Cidades Atendidas</button>
					<select id="joao" hidden></select>
				</div>
				<div id="repre" align="middle"><b>REMACOL</b><br><br>
					<p>(47) 3339 1193</p>
					<p>remacol@terra.com.br</p><br>
					<p>Blumenau e Região</p>
					<button id="exibirComboboxremacol">Mostrar Cidades Atendidas</button>
					<select id="remacol" hidden></select>
				</div>
				<div id="repre" align="middle"><b>JAIRO SCHNEIDER</b><br><br>
					<p>(54) 9 8437-9269/9 9986-5589</p>
					<p>jairoschneider@globo.com</p><br>
					<p>Carazinho e Região</p>
					<button id="exibirComboboxjairo">Mostrar Cidades Atendidas</button>
					<select id="jairo" hidden></select>
				</div>
				<div id="repre" align="middle"><b>MAXI VENDA</b><br><br>
					<p>(51) 3077-9772/(51) 99127-6696</p>
					<p>emerson@maxivenda.com.br</p><br>
					<p>Porto Alegre e Região</p>
					<button id="exibirComboboxmaxivenda">Mostrar Cidades Atendidas</button>
					<select id="maxivenda" hidden></select>
				</div>
				<div id="repre" align="middle"><b>AFONSO SPOHR</b><br><br>
					<p>(55) 9 9912-9650</p>
					<p>afonso.inacio@bol.com.br</p><br>
					<p>Santa Rosa e Região</p>
					<button id="exibirComboboxafonso">Mostrar Cidades Atendidas</button>
					<select id="afonso" hidden></select>
				</div>
				<div id="repre" align="middle"><b>FRACARO</b><br><br>
					<p>(45) 3226-4679</p>
					<p>fracaro.rep@uol.com.br</p><br>
					<p>Cascavel e Região</p>
					<button id="exibirComboboxfracaro">Mostrar Cidades Atendidas</button>
					<select id="fracaro" hidden></select>
				</div>
				<div id="repre" align="middle"><b>RECROL</b><br><br>
					<p>(43) 3256-3830</p>
					<p>recrol@recrol.com.br</p><br>
					<p>Maringá e Região</p>
					<button id="exibirComboboxrecrol">Mostrar Cidades Atendidas</button>
					<select id="recrol" hidden></select>
				</div>
				<div id="repre" align="middle"><b>GRANTOK</b><br><br>
					<p>(49) 3434-0493 / 3434-0605</p>
					<p>atendimento@grantok.com.br</p><br>
					<p>Demais cidades</p>
				</div>
			</div>
		</section>
		<footer>
			<div id="footer">
				<div id="contato">
					<br>
					<h2>Contato</h2>
					<br>
					<p>(49) 3434-0493<br><br>
					(49) 3434-0605<br><br></p>
					<p>atendimento@grantok.com.br</p>
				</div>
				<div id="endereco">
					<br>
					<h2>Endereço</h2>
					<br>
					<p>Rua Sete de Setembro, 01 - Centro<br><br>
					Vargeão-SC<br><br>
					89690-000</p>
				</div>
				<div id="autoria">
					<p>Grantok - Todos os direitos reservados | Copyright 2018 <a href="https://www.facebook.com/mauricio.spagnol.9">Maurício Spagnol</a><b>Desenvolvido por: </b></p>
				</div>
			</div>
		</footer>
	</div>

</body>
</html>	