<!DOCTYPE html>
<html lang="pt" amp>
<head>
	<meta charset="UTF-8">
	<title>Grantok Portas & Cabos</title>
	<link rel="alternate" hreflang="pt-br" href="alternateURL">
	<link rel="canonical" href="index.html">	
	<link rel="stylesheet" type="text/css" href="css/style.css">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<script type="text/javascript" src="js/troca-representantes.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script type="text/javascript" src="js/comboboxcidades.js"></script>	
	<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, maximum-scale=1,minimum-scale=1, user-scalable=no" />

	<script type="application/ld+json">
  		{
			"@context": "http://schema.org",
			"@type": "WebPage",
  			"publisher": "Maurício Spagnol"
  		}
  	</script>

<style amp-custom>
  body {
    background-color: white;
  }
</style>

<script type="text/javascript" src="js/scrolltop.js"></script>

</head>
<body>
	<div id="geral">
		<?php
			include("menu.php")
		?>
		<a href="#" class="scrollToTop"></a>
		<section>
			<!-- Image Map Generated by http://www.image-map.net/ -->
			<img src="/img/mapa.png" usemap="#image-map" class="mapa" alt="mapa">

			<map itemprop="location" name="image-map">
			    <area onmouseover="repre(1)" target="" alt="Felix" title="Felix" href="" coords="196,190,203,192,214,189,223,197,235,195,237,216,230,218,230,233,223,233,213,235,207,232,200,236,189,234,195,219,191,208,191,206" shape="poly">
			    <area onmouseover="repre(2)" target="" alt="Silvio" title="Silvio" href="" coords="237,195,238,214,232,219,231,234,243,238,252,238,262,240,273,242,274,234,362,224,375,178,354,181,347,177,337,186,331,190,321,189,310,195,313,204,308,210,300,207,285,204,274,205,265,199" shape="poly">
			    <area onmouseover="repre(3)" target="" alt="Adriano" title="Adriano" href="" coords="277,236,340,230,352,250,349,257,345,265,313,294,312,316,282,315,283,292,291,267,287,253,276,245" shape="poly">
			    <area onmouseover="repre(4)" target="" alt="Everton" title="Everton" href="" coords="341,229,388,227,404,255,352,254,353,245" shape="poly">
			    <area onmouseover="repre(5)" target="" alt="Joao" title="Joao" href="" coords="345,269,358,293,403,259,354,257" shape="poly">
			    <area onmouseover="repre(6)" target="" alt="Remacol" title="Remacol" href="" coords="391,227,436,211,438,218,438,224,441,237,440,245,414,245,407,255" shape="poly">
			    <area onmouseover="repre(9)" target="" alt="Afonso" title="Afonso" href="" coords="137,258,145,281,161,293,177,297,190,309,193,323,187,329,185,345,190,349,181,353,140,353,125,341,119,325,100,319,96,329,76,331,78,320,86,301,118,274" shape="poly">
    			<area onmouseover="repre(3)" target="" alt="Adriano" title="Adriano" href="" coords="250,239,234,270,227,272,224,284,240,292,254,286,254,268,265,250,278,248" shape="poly">
    			<area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="242,294,258,307,265,324,262,335,262,357,267,367,281,366,295,353,296,338,307,330,308,320,325,309,333,283,307,258,281,250,265,259" shape="poly">
				<area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="367,299,381,302,388,307,375,316,372,336,385,340,411,319,432,306,432,296,421,285,396,280" shape="poly">
    			<area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="332,190,333,201,356,209,367,217,363,231,376,228,399,233,410,229,410,217,425,208,436,204,443,189,438,176,412,177,398,189,376,178,351,180" shape="poly">
				<area onmouseover="repre(8)" target="" alt="Maxi Venda" title="Maxi Venda" href="" coords="312,326,326,322,345,319,350,308,356,299,342,298,334,287" shape="poly">
    			<area onmouseover="repre(8)" target="" alt="Maxi Venda" title="Maxi Venda" href="" coords="310,329,336,339,339,348,348,355,367,372,352,401,313,382,284,368,296,358,297,339" shape="poly">
    			<area onmouseover="repre(12)" target="" alt="Grantok" title="Grantok" href="" coords="322,329,339,336,342,343,368,368,382,345,367,339,373,328,375,314,386,308,361,301,348,319" shape="poly">
    			<area onmouseover="repre(14)" target="" alt="Fabricio" title="Fabricio" href="" coords="289,374,263,375,263,382,259,395,269,403,256,407,264,415,265,429,261,435,267,469,273,477,324,444,351,402" shape="poly">
    			<area onmouseover="repre(8)" target="" alt="Maxi Venda" title="Maxi Venda" href="" coords="268,480,257,451,254,436,260,428,262,417,245,416,214,424,224,443,239,444,246,454,247,472,241,481,255,502" shape="poly">
    			<area onmouseover="repre(13)" target="" alt="Geovani" title="Geovani" href="" coords="141,257,186,233,244,240,233,266,224,270,223,283,249,299,264,324,265,363,257,397,252,407,216,420,221,441,239,446,245,469,239,483,255,502,247,535,212,560,208,533,216,503,103,419,83,430,80,416,41,382,7,389,68,320,80,334,98,332,104,321,117,328,123,343,142,353,181,354,195,349,187,341,192,325,198,313,177,290,165,294,147,278" shape="poly">
			</map>
			<div>
				<div id="representante_atual">
					<b><p align="middle" id="nome-repre-atual"></p></b><br>
					<p align="middle" id="telefone-repre-atual"></p><br>
					<p align="middle" id="e-mail-repre-atual"></p>
				</div>
				<h2 align="middle" id="titulo-representantes">Todos Representante</h2>
				<br>
				<div id="repre" align="middle"><b>FÉLIX SPEROTTO</b><br><br>
					<p>(49) 9 9917-1696</p>
					<p>dibisperotto@yahoo.com.br</p><br>
					<p>São Miguel do Oeste e Região</p>
					<button id="exibirComboboxfelix">Mostrar Cidades Atendidas</button>
					<select id="felix" hidden></select>
				</div>
				<div id="repre" align="middle"><b>SILVIO ZANCAN</b><br><br>
					<p>(49) 9 9202-0031</p>
					<p>silviofzancan@gmail.com</p><br>
					<p>Chapecó e Região</p>
					<button id="exibirComboboxsilvio">Mostrar Cidades Atendidas</button>
					<select id="silvio" hidden></select>
				</div>
				<div id="repre" align="middle"><b>ADRIANO BRITO</b><br><br>
					<p>(49) 9 9142-0302/3444-9870</p>
					<p>adrianorepre.vendas@gmail.com</p><br>
					<p>Concórdia e Região</p>
					<button id="exibirComboboxadriano">Mostrar Cidades Atendidas</button>
					<select id="adriano" hidden></select>
				</div>
				<div id="repre" align="middle"><b>EVERTON LONGEN</b><br><br>
					<p>(47) 9 9105-3859</p>
					<p>evertongrando@hotmail.com</p><br>
					<p>Rio do Sul e Região</p>
					<button id="exibirComboboxeverton">Mostrar Cidades Atendidas</button>
					<select id="everton" hidden></select>
				</div>
				<div id="repre" align="middle"><b>JOÃO STEFANELLO</b><br><br>
					<p>(49) 9 9107-8009</p>
					<p>joao.stefanello@gmail.com</p><br>
					<p>Lages e Região</p>
					<button id="exibirComboboxjoao">Mostrar Cidades Atendidas</button>
					<select id="joao" hidden></select>
				</div>
				<div id="repre" align="middle"><b>REMACOL</b><br><br>
					<p>(47) 3339 1193</p>
					<p>remacol@terra.com.br</p><br>
					<p>Blumenau e Região</p>
					<button id="exibirComboboxremacol">Mostrar Cidades Atendidas</button>
					<select id="remacol" hidden></select>
				</div>
				<div id="repre" align="middle"><b>JAIRO SCHNEIDER</b><br><br>
					<p>(54) 9 8437-9269/9 9986-5589</p>
					<p>jairoschneider@globo.com</p><br>
					<p>Carazinho e Região</p>
					<button id="exibirComboboxjairo">Mostrar Cidades Atendidas</button>
					<select id="jairo" hidden></select>
				</div>
				<div id="repre" align="middle"><b>MAXI VENDA</b><br><br>
					<p>(51) 3077-9772/(51) 99127-6696</p>
					<p>emerson@maxivenda.com.br</p><br>
					<p>Porto Alegre e Região</p>
					<button id="exibirComboboxmaxivenda">Mostrar Cidades Atendidas</button>
					<select id="maxivenda" hidden></select>
				</div>
				<div id="repre" align="middle"><b>AFONSO SPOHR</b><br><br>
					<p>(55) 9 9912-9650</p>
					<p>afonso.inacio@bol.com.br</p><br>
					<p>Santa Rosa e Região</p>
					<button id="exibirComboboxafonso">Mostrar Cidades Atendidas</button>
					<select id="afonso" hidden></select>
				</div>
				<div id="repre" align="middle"><b>FRACARO</b><br><br>
					<p>(45) 3226-4679</p>
					<p>fracaro.rep@uol.com.br</p><br>
					<p>Cascavel e Região</p>
					<button id="exibirComboboxfracaro">Mostrar Cidades Atendidas</button>
					<select id="fracaro" hidden></select>
				</div>
				<div id="repre" align="middle"><b>Geovani de Carvalho</b><br><br>
					<p>(55) 9 9656-2747</p>
					<p>geovanicarvalhorepresentacoes
						      @gmail.com</p><br>
					<p></p>
					<button id="exibirComboboxGeovani">Mostrar Cidades Atendidas</button>
					<select id="geovani" hidden></select>
				</div>
				<div id="repre" align="middle"><b>Fabricio</b><br><br>
					<p>(51) 9 8284-2260</p>
					<p>fffvt@terra.com.br</p><br>
					<p></p>
					<button id="exibirComboboxFabricio">Mostrar Cidades Atendidas</button>
					<select id="fabricio" hidden></select>
				</div>
				<div id="repre" align="middle"><b>GRANTOK</b><br><br>
					<p>(49) 3434-0493 / 3434-0605</p>
					<p>atendimento@grantok.com.br</p><br>
					<p>Demais cidades</p>
				</div>
			</div>
		</section>
		<footer>
			<div id="footer">
				<div id="contato">
					<br>
					<h2>Contato</h2>
					<br>
					<p>(49) 3434-0493<br><br>
					(49) 3434-0605<br><br></p>
					<p>atendimento@grantok.com.br</p>
				</div>
				<div id="endereco">
					<br>
					<h2>Endereço</h2>
					<br>
					<p>Rua Sete de Setembro, 01 - Centro<br><br>
					Vargeão-SC<br><br>
					89690-000</p>
				</div>
				<div id="autoria">
					<p>Grantok - Todos os direitos reservados | Copyright 2018 <a href="https://criasystem.tech/">Maurício Spagnol</a><b>Desenvolvido por: </b></p>
				</div>
			</div>
		</footer>
	</div>

</body>
</html>	